project_name: hy-motion-cli
builds:
  - id: hy-motion-cli
    main: ./src/main.go
    binary: hy-motion-cli
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    hooks:
      post:
        - cmd: upx -9 "{{ .Path }}"
          filters:
            exclude:
              - '^windows-arm'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^meta:'
