project_name: hy-motion-cli
builds:
  - id: hy-motion-cli
    main: ./src/main.go
    binary: hy-motion-cli
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/hproof/hy-motion-cli/commands.cliVersion={{.Version}}
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^meta:'
